### PR TITLE
Add seperate columns for From and To fields; show Date and Time

### PR DESCRIPTION
**Pull request by schoerg**
I found it more useful to see both `From` and `To` fields in the message list.

### CODE REVIEW

**Comment by Dijji** [comment]
Hi

Your code is very good, and certainly of the right quality to merge. However, I don’t agree with the proposed changes, and here’s why. 

My intent was to follow the Outlook defaults precedent. Given limited space, Outlook shows either From or To for each email, depending whether it has been received or sent. For time, it shows time-of-day for very recent emails, day of the week for emails received this week, and otherwise the short date. I emulated this by showing either From or To, in the same way, and simplified the time by just showing the short date for everything.

Of course, a full email client would let you configure what properties were shown, but given that that is beyond my scope, I still think that I am in about the right place in following the Outlook precedent. Also, given that the source is open, developers at least can do what you have done and change things to suit themselves.

So I am currently proposing not to merge these changes, but please feel free to tell me why I am wrong.

Dijji

**Comment by Dijji** [comment]
Your scenario is very valid, though. Perhaps what I should do is to again follow the Outlook example and show the additional information (date/time, from or to, whichever was not shown, plus the copy and blind copy lists) in a variable height panel above the body of the selected email.

Would that have helped you?

Dijji

**Comment by schoerg** [comment]
Probably not, but I can't say for sure now. I haven't checked much of the content of the mails. I don't use Outlook, so I had no idea that you tried to follow their style.

**Comment by flywire** [comment]
@schoerg re 01729f3 - done at 1090d3f

**Comment by Dijji** [comment]
As flywire notes, displaying both date and time has now made it into master, after some further discussion, as has showing Outlook style header information above the contents of the email.

I still don't agree with separate From and To columns, though. It would consume more space, and in most cases, the only information added would be my own name, which I should already know.

Thank you again for your input. It is through suggestions and constructive discussion that programs improve.

Dijji

**Pull request closed without merging**
