### PR TITLE
Encrypted/Signed Email  changes for Issue #15

### PR DESCRIPTION
**Pull request by just1fi3d**
see #15

### CODE REVIEW

**Comment by Dijji** [comment]
Congratulations on reaching the finishing line!

But why does the pull request contain 25 commits some of them my own? I was expecting something with just the changes you have made.

Also, the nicest form of pull request is a branch within your fork. That makes it easy for me to pull it into a branch in my own repo, check it out, then merge it into master if all is well.

**Comment by Dijji** [comment]
Having dug around, I find I can change the target branch for your request. So I am urging it to a branch called SecureMail for full examination

**Comment by just1fi3d** [comment]
Sorry I didn't get a chance to look at this yesterday. I was afk. This was
the first pull request I've done so I'm guessing I somehow included your
commits with mine.  Thanks for the tip on using a branch will do in the
future!

**Comment by Dijji** [comment]
I think what happened is that you made your commit, and then synchronised with the original repository. Because you had made a change, the commits brought over were regarded as new, because they had a different baseline. Then I get a whole raft of them, which are reluctant to apply because how do I know exactly what they will do without carefully examining each one?

Best practice is never to make the changes to master, but always to some branch off master. It is ideal if you synchronise your master with the original before you branch, but that is not necessary. If your master corresponds with any historical state of mine, the pull request will be easy to handle.

At the moment I'm looking at git cherry-pick to see if I can get back to just your change. And afterwards, I get to look in the code!

**Comment by Dijji** [comment]
Okay, sorted. My repository now has a branch called SecureEmail, with just your changes in. Tomorrow I will look at the code.

**Comment by just1fi3d** [comment]
Thanks! Sorry for the extra hassle.

**Pull request merged**
