### PR TITLE
UpdateView functions in View and FolderView

### PR DESCRIPTION
**Pull request by iluvadev**
I think all runs ok, at least in the manual tests I have done.
I made some minor changes: 
XstFile:
	+ New property: RootFolder (with the root of the current Folder Tree)
	+ Modification in ReadMessages: Automatically add the Messages to Folder 

FolderView:
	+ New function: UpdateMessageViews (updates MessageViews list with Messages in Folder)

View:
	+ New function: UpdateFolderViews (updates FolderViews list with Folders inside RootFolder)
	
MainWindow:
	+ Some changes in reading root folder stucture and messages in a folder (commented in code)

### CODE REVIEW

**Comment by Dijji** [comment]
These changes are mostly all to the good. I don't agree with adding the RootFolder property, though, as I think the core's caller should be in control of the lifetime of the data read from the Outlook file, and adding this property holds it in memory in a way that is both opaque and unavoidable. I do agree with setting the Folder property in Message where you do, but I think I would have used a .ForEach clause in the Linq statement to avoid an additional loop construct.

Also, there is no need to leave old code in place commented out, the differencer tells me what has changed quite clearly. It is better just to change the code to what you think it should be, so that it is ready for check-in, and leave any explanation in the pull request's comments.

What do you think we should do next with these changes?

I am currently working on testing the core API by adding a second client in the form of a command line export tool, starting from the baseline provided by another contributor.

**Comment by Dijji** [comment]
The updated changes all look good to me. There are a bunch of definite improvements. I am curious, though, why you introduce the Internal restriction on things like NIDs?

**Comment by iluvadev** [comment]
Hey, sorry, I haven't written it before ... I thought you wouldn't see it if I didn't make a new pull-request ... I'm new to git 

I think the properties and methods should be visible only where they should be used. All the properties were public, but I think that some are just for internal structures and data. I think this information is only for the Core. UI works with processed and structured by the Core.
Maybe is not important...
In the case of defining a public API, it is important to have good control over everything that can be “seen” outside, to avoid mistakes and misuses.

**Comment by iluvadev** [comment]
The main changes I have made are:
- I have changed the access modifiers of some properties of the XstFile, Folder, Message and Attachment classes to 'internal': I think these properties are only for internal use in Core (BTree for example)
- I changed some foreach loops for Linq expressions or for 'list.AddRange(ienumerable.ToList())'. But I think the improvement is minimal
- The class Attachment has a property with the Message (I changed the name from "Parent" to "Message"), and the Message has a property with the Folder. I added a new Property in Folder: "ParentFolder". In this way, we allow a possible navigation between ParentFolder<->Folder<->Message<->Attachment. With this information, we can know the Folder's "Path" (new property).
- I moved the XstFile property from Attachment to Folder

I have tested and I think everything works fine.

**Comment by Dijji** [comment]
I like it! Accepting the pull. Thank you very much.

**Comment by Dijji** [comment]
FYI:  I am pushing this towards release - the Divided branch contains the latest candidate, with a few more changes:
- XstReader.Core is now XstReader.Base, to avoid confusion with .Net Core
- The DLL is still built by the solution, but no longer used by XstReader or XstExport in order to maintain the existing 'needs nothing but the executable' model
- As well as XstExport, the solution builds XstPortableExport, which is exactly the same command line tool, but built for .Net Core 2.1, with some loss of functionality in areas that would require framework references and so tie it to Windows, specifically RTF and MIME decryption. This also provides a sample showing one way to embed XstReader.Base in a Core program.

**Comment by iluvadev** [comment]
Perferct!
I'm playing with the code in my fork to understand it. I'm trying to do some more improvements.
I'm enjoying with your project 😄

**Comment by Dijji** [comment]
I have now shipped all these changes as Release 1.14, so everything is now back in master.

Thanks again for your contribution. It is much appreciated.

**Pull request merged**
